Make the library a package
nu-radio/cr-pulse-interpolator pull request #7
Opened 2024-02-15 13:26 UTC by bekaertruben

These changes would make the package installable with `pip install git+https://github.com/nu-radio/cr-pulse-interpolator`.  
Please review the information in the `pyproject.toml` file.

2024-02-28 13:10 UTC, MijnheerD requested changes
Before we can merge, I think the demo files need to updated with the correct imports as well, no?

2024-02-28 13:10 UTC, MijnheerD commented on pyproject.toml
This looks good! It installed without problem on my local installation. Though is there no way to lower the Python 3.8 requirement?

2024-03-04 06:30 UTC, bekaertruben commented on pyproject.toml
I've made the requested changes, including lowering python requirement.
Note though that versions older than 3.8 are end-of-life, and may be insecure

2024-03-04 16:02 UTC, MijnheerD approved these changes
Looks clean, thanks for the work!

2024-03-04 16:04 UTC, MijnheerD commented
Oh, so apparently I don't have the rights to review it for merger :-( 

@acorstanje or @anelles , could you please put your review in?

2024-03-04 16:51 UTC, anelles commented
@MijnheerD can you now? (working on the settings)

2024-03-05 10:02 UTC, MijnheerD commented
@anelles Yes, it works now 💯 My review has granted merge access to the PR. 

@bekaertruben , usually we handle a 24h waiting period between the review and actually merging the changes, so feel free to merge later today!

2024-03-06 12:35 UTC, merged